[theme]
base = "dark"
primaryColor = "#2563EB"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
runOnSave = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
